services:

  auth_service:
    build: ./Backend/auth_service
    ports:
      - "8000:8000"

  doctor_service:
    build: ./Backend/doctor_service
    ports:
      - "8001:8001"

  patient_service:
    build: ./Backend/patient_service
    ports:
      - "8002:8002"

  appointment_service:
    build: ./Backend/appointment_service
    ports:
      - "8003:8003"

  media_service:
    build: ./Backend/media_service
    ports:
      - "8004:8004"

  payment_service:
    build: ./Backend/payment_service
    ports:
      - "8005:8005"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
      - doctor_service
      - patient_service
      - appointment_service
      - media_service
      - payment_service