version: '3.9'

services:
 
  # ================= DOCTOR SERVICE =================
  doctor_service:
    build: ./doctor_service
    container_name: doctor_service
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./doctor_service/media:/app/media    # Neon Postgres URL
    secrets:
      - doctor_private_key
      - doctor_public_key
    restart: always

 