# Generated by Django 4.2.25 on 2026-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.BigIntegerField(unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("medical_history", models.TextField()),
                ("additional_information", models.TextField()),
            ],
        ),
    ]
