worker_processes 1;

events {
    worker_connections 1024;
}

http {

    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {

        listen 80;
        client_max_body_size 50M;

        # AUTH SERVICE
        location /users/api/ {
            proxy_pass https://auth-service-06sf.onrender.com/users/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # DOCTOR SERVICE
        location /doctor/api/ {
            proxy_pass https://doctor-service-1vnw.onrender.com/doctor/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # PATIENT SERVICE
        location /patient/api/ {
            proxy_pass https://patient-service-hkth.onrender.com/patient/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # APPOINTMENT SERVICE
        location /appointment/api/ {
            proxy_pass http://appointment_service:8003/appointment/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MEDIA SERVICE
        location /media/api/ {
            proxy_pass http://media_service:8004/media/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # PAYMENT SERVICE
        location /payment/api/ {
            proxy_pass https://payment-service-phn5.onrender.com/payment/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # REACT FRONTEND
        location / {
            proxy_pass http://frontend:3000;
        }

        # STATIC MEDIA
        location /media/ {
            proxy_pass http://doctor_service:8001;
        }

        # WEBSOCKET
        location /ws/ {
            proxy_pass http://media_service:8004;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}