# Generated by Django 4.2.25 on 2026-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("speciality", models.TextField(blank=True, default="nill", null=True)),
                ("license_no", models.CharField(blank=True, null=True)),
                (
                    "organization_name",
                    models.TextField(blank=True, default="nill", null=True),
                ),
                ("location", models.TextField(blank=True, default="nill", null=True)),
                ("phone_number", models.CharField(blank=True, null=True)),
                ("experiance", models.IntegerField(default=0, null=True)),
                (
                    "available_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("offline", "Offline"),
                            ("in_consultation", "In Consultation"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_images/default_avatar.png", upload_to="image/"
                    ),
                ),
                ("amount", models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
