# Generated by Django 4.2.25 on 2025-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("speciality", models.TextField(blank=True, default="nill", null=True)),
                ("license_no", models.IntegerField(blank=True, null=True)),
                (
                    "organization_name",
                    models.TextField(blank=True, default="nill", null=True),
                ),
                ("location", models.TextField(blank=True, default="nill", null=True)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                ("experiance", models.IntegerField(default=0, null=True)),
                ("available_status", models.TextField(null=True)),
                (
                    "image",
                    models.ImageField(
                        default="default_images/default_avatar.png", upload_to="image/"
                    ),
                ),
            ],
        ),
    ]
