# Generated by Django 4.2.25 on 2025-11-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="available_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("busy", "Busy"),
                    ("offline", "Offline"),
                    ("in_consultation", "In Consultation"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
