# Generated by Django 4.2.25 on 2025-11-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_alter_doctormodel_available_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="license_no",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctormodel",
            name="phone_number",
            field=models.CharField(blank=True, null=True),
        ),
    ]
