# Generated by Django 4.2.25 on 2025-12-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_alter_doctormodel_license_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctormodel",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
