# Generated by Django 4.2.25 on 2025-12-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_doctormodel_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
