# Generated by Django 4.2.25 on 2025-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_alter_doctormodel_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="amount",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
