# Generated by Django 4.2.25 on 2025-12-21 15:33

import appointment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointmentmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField()),
                ("doctor_id", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("note", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("pending", "pending"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("refer_doctor_id", models.IntegerField(blank=True, null=True)),
                (
                    "referrence_no",
                    models.CharField(
                        blank=True,
                        default=appointment.models.Appointmentmodel.create_new_ref_number,
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="appointment.appointmentmodel",
                    ),
                ),
            ],
        ),
    ]
